INSERT INTO users (name, age) VALUES ("Bob", 20);
INSERT INTO users (name, age) VALUES ("Bobo", 21);
INSERT INTO users (name, age) VALUES ("Borb", 22);
INSERT INTO users (name, age) VALUES ("Cob", 23);
INSERT INTO users (name, age) VALUES ("Blob", 24);
INSERT INTO users (name, age) VALUES ("Rob", 25);
INSERT INTO users (name, age) VALUES ("Bob2", 26);
INSERT INTO users (name, age) VALUES ("Bob3", 27);
INSERT INTO users (name, age) VALUES ("Bob4", 28);
INSERT INTO users (name, age) VALUES ("Bob5", 29);
INSERT INTO users (name, age) VALUES ("Bob6", 30);
INSERT INTO users (name, age) VALUES ("Bob7", 31);
INSERT INTO users (name, age) VALUES ("Bob8", 32);
INSERT INTO users (name, age) VALUES ("Bob9", 33);
INSERT INTO users (name, age) VALUES ("Rob2", 34);
INSERT INTO users (name, age) VALUES ("Rob3", 35);
INSERT INTO users (name, age) VALUES ("Rob4", 36);
INSERT INTO users (name, age) VALUES ("Rob5", 37);
INSERT INTO users (name, age) VALUES ("Rob6", 38);
INSERT INTO users (name, age) VALUES ("Rob7", 39);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("stuff", "stuff2", 50, "11-20-18", "11-20-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("stuf", "stuff3", 60, "11-20-17", "11-20-18");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("stu", "stuff4", 70, "11-20-16", "11-20-17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("qwfq", "sqwf", 80, "11-10-17", "11-20-28");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("egw", "gweg", 90, "11-20-17", "11-20-20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("erge", "wgrw", 100, "11-20-17", "11-20-21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("sds", "stuff3", 160, "11-20-17", "11-20-22");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("bevew", "stuff3", 260, "11-20-17", "11-20-23");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("asfas", "stuff3", 360, "11-20-17", "11-20-24");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("asfase", "stuff3", 460, "11-20-17", "11-20-25");


INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 12, 21);
INSERT INTO pledges (amount, user_id, project_id) VALUES (21, 11, 22);
INSERT INTO pledges (amount, user_id, project_id) VALUES (22, 13, 23);
INSERT INTO pledges (amount, user_id, project_id) VALUES (23, 14, 24);
INSERT INTO pledges (amount, user_id, project_id) VALUES (24, 15, 25);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 16, 26);
INSERT INTO pledges (amount, user_id, project_id) VALUES (26, 17, 27);
INSERT INTO pledges (amount, user_id, project_id) VALUES (27, 18, 28);
INSERT INTO pledges (amount, user_id, project_id) VALUES (28, 11, 29);
INSERT INTO pledges (amount, user_id, project_id) VALUES (29, 21, 31);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 22, 32);
INSERT INTO pledges (amount, user_id, project_id) VALUES (31, 23, 33);
INSERT INTO pledges (amount, user_id, project_id) VALUES (32, 24, 34);
INSERT INTO pledges (amount, user_id, project_id) VALUES (33, 25, 35);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34, 26, 36);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (36, 2, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (37, 3, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (32, 4, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34, 6, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (33, 7, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (32, 8, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (31, 9, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (301, 10, 32);
INSERT INTO pledges (amount, user_id, project_id) VALUES (302, 20, 39);
INSERT INTO pledges (amount, user_id, project_id) VALUES (303, 21, 35);
INSERT INTO pledges (amount, user_id, project_id) VALUES (303, 22, 35);
INSERT INTO pledges (amount, user_id, project_id) VALUES (303, 22, 35);
INSERT INTO pledges (amount, user_id, project_id) VALUES (303, 22, 35);
